micronaut:
  application:
    name: velocityTutorial
  router:
      static-resources:
        default:
          enabled: true
          mapping: /public/**
          paths:
            - classpath:public
netty:
  default:
    allocator:
      max-order: 3
